[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
headless = true
port = 8501
runOnSave = false
maxUploadSize = 50
maxMessageSize = 100

[browser]
gatherUsageStats = false

[logger]
level = "info"

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[client]
showErrorDetails = true
caching = true
displayEnabled = true 