[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
headless = true
port = 8501
runOnSave = false

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
showErrorDetails = true
caching = true

[global]
developmentMode = false
disableWatchdogWarning = true 